import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '../components/Nav'
import Cards from '@/components/Cards'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GeoTemp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-800 text-slate-100`}>
      <Nav />
        {children}
      <Cards/>
      </body>
    </html>
  )
}
