import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/components/Provider'
import Nav from '../components/Nav'
import Cards from '@/components/Cards'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GeoTemp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
      <body className={`${inter.className} bg-slate-800 text-slate-100 flex flex-col h-screen`}>
      <Nav />
        {children}
      {/* <Cards/> */}
      </body>
    </Provider>
    </html>
  )
}
